stages:
  - dockerize
  - deploy

.base_rules:
  rules:
    - &alpha_tag # if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+-alpha.\d+$/
      if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
      variables:
        ENVIRONMENT: 'testing'
        ENVIRONMENT_URL: 'https://cms-api-testing.vesatogo.in'
        APP_VERSION: $CI_COMMIT_TAG

dockerize:
  stage: dockerize
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  environment:
    name: $ENVIRONMENT
    url: $ENVIRONMENT_URL
  variables:
    BASE_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/api
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $BASE_IMAGE:latest -t $BASE_IMAGE:$APP_VERSION .
    - docker image push -a $BASE_IMAGE
  rules:
    - *alpha_tag

deploy:
  stage: deploy
  environment:
    name: $ENVIRONMENT
    url: $ENVIRONMENT_URL
  before_script:
    - wget https://storage.googleapis.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl config get-contexts
  script:
    - echo "Restart Kubernetes"
    - kubectl config use-context vesatogo/$CI_PROJECT_NAME:internal-tools
    - kubectl rollout restart deployment/cms-api-app -n tools
  rules:
    - *alpha_tag
