version: '3'

services:
  app:
    build: .
    container_name: vt-cms
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://db/payload
  db:
    image: mongo
    container_name: vt-mongo
    restart: always
    volumes:
      - db:/data/db

volumes:
  db:
