name: CI/CD for Roster Project

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  dockerize:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: 'testing'
      ENVIRONMENT_URL: 'https://cms-api-testing.vesatogo.in'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get Git tag
        id: get_tag
        run: echo ::set-output name=tag::$(echo "${GITHUB_REF#refs/tags/}")

      - name: Build image
        run: docker build -t ${{ secrets.CONTIANER_REGISTRY }}/roosterashutosh:${{ steps.get_tag.outputs.tag }} .

      - name: Logging to DO Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Push image
        run: docker push ${{ secrets.CONTIANER_REGISTRY }}/roosterashutosh:${{ steps.get_tag.outputs.tag }}