name: CI/CD for Roster Project

on:
  push:
    branches:
      - main
  # Trigger the workflow when a new tag matching the pattern is created
  # push:
  #   tags:
  #     - 'v*.*.*'

jobs:
  dockerize:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: 'testing'
      ENVIRONMENT_URL: 'https://cms-api-testing.vesatogo.in'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # - name: Buil Docker image
      #   run: 
      #     docker build -t piyushpangavhane/rooster:latest .
      #     docker push piyushpangavhane/rooster:latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: piyushpangavhane/rooster:latest